language: php

services:
    - docker
    
php:
  - 5.5
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
    
notifications:
  slack: 
    rooms:
      - esgi-iw:3xesgTA7LDncYCqnA2EShdA5#git
    on_success: always
    on_failure: always
    
  email:
    recipients:
      - saittirite@myges.fr
      
script:
    - docker run --rm -v $PWD:/src phpqa/php-cs-fixer fix . --dry-run
