version: '3'
services:
    mysql:
        image: 'mariadb:latest'
        volumes:
            - './sql/init.sql:/docker-entrypoint-initdb.d/init.sql'
        environment:
            - MYSQL_DATABASE=docker
            - MYSQL_USER=docker
            - MYSQL_PASSWORD=docker
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
    adminer:
        image: 'adminer:latest'
        ports:
            - '8081:8080'
        depends_on:
            - mysql
    php:
        image: 'okty/php:7.2'
        volumes:
            - './:/usr/share/nginx/html'
        environment:
            - 'PHP_EXTENSIONS=pdo_mysql,intl,opcache'
    nginx:
        build:
          context: ./
        ports:
            - '8080:80'
        volumes:
            - './:/usr/share/nginx/html'
        environment:
            - MAX_UPLOAD_SIZE=2M
            - PHP_CONTAINER_ID=php
            - INDEX_SUBFOLDER=web
        depends_on:
            - php
            - mysql
